apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-new
  namespace: venture-staging
  labels:
    app: venture-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn # Using Longhorn for resize support
