apiVersion: v1
kind: Service
metadata:
  name: venture-redis
  namespace: venture-staging
spec:
  selector:
    app: venture-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
