apiVersion: v1
kind: Secret
metadata:
  name: venture-env-secrets
  namespace: venture-staging
type: Opaque
stringData:
  NODE_ENV: "development"
  DATABASE_URL: "postgres://user:pass@host:port/db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: venture-staging
type: Opaque
stringData:
  password: "changeme"
